name = ""
name_language = "en"
multicast_ip = "224.0.0.167" # https://en.wikipedia.org/wiki/Multicast_address

[receive]
directory = "uploads"
max_file_size = 1000000000
save_user_id = 0
save_group_id = 0
clipboard = false
allowed_ips = []  # allows all IPs if this is empty

[send]
directory = "uploads"

[functions]
http_file_server = true
local_send_server = true

[logging]
no_color = false
level = "info"