name = ""
name_language = "en"

[receive]
directory = "uploads"
save_user_id = 0
save_group_id = 0
clipboard = false

[functions]
http_file_server = true
local_send_server = true

[logging]
no_color = false
level = "info"